ThucHanhLanCuoi/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThucHanhLanCuoi.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult spad1()
        {
            return View();
        }
        public ActionResult spad2()
        {
            return View();
        }
        public ActionResult spad3()
        {
            return View();
        }
        public ActionResult spad4()
        {
            return View();

        }
        public ActionResult spad5()
        {
            return View();
        }
        public ActionResult spad6()
        {
            return View();
        }
        public ActionResult spad7()
        {
            return View();
        }
        public ActionResult spad8()
        {
            return View();
        }
        public ActionResult spad9()
        {
            return View();
        }
        public ActionResult spad10()
        {
            return View();
        }
    }
}

ThucHanhLanCuoi/Controllers/GiayNikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThucHanhLanCuoi.Controllers
{
    public class GiayNikeController : Controller
    {
        // GET: GiayNike
        public ActionResult spnk1()
        {
            return View();
        }
        public ActionResult spnk2()
        {
            return View();
        }
        public ActionResult spnk3()
        {
            return View();
        }
        public ActionResult spnk4()
        {
            return View();
        }
        public ActionResult spnk5()
        {
            return View();
        }
        public ActionResult spnk6()
        {
            return View();

        }
        public ActionResult spnk7()
        {
            return View();

        }
        public ActionResult spnk8()
        {
            return View();

        }
        public ActionResult spnk9()
        {
            return View();

        }
    }
}

ThucHanhLanCuoi/Controllers/TrangGiayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThucHanhLanCuoi.Controllers
{
    public class TrangGiayController : Controller
    {
        public ActionResult TrangNike()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult TrangBlog()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult LienHe()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult TrangAdidas()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult TrangAsics()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult TrangGiayTheThao()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult TrangLacoste()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult TrangPuma()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult TrangSale()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ThucHanhLanCuoi/Views/TrangGiay/TrangAdidas.cshtml
@{
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Shoes</title>
    <link rel="stylesheet" href="~/CSS/Product.css">
    <link rel="stylesheet" href="~/CSS/ThanhICON.css">
</head>
<body>
    <h1 class="page-title">Siêu Sale Giày Adidas</h1>

    <div class="products-section">
        <h2 class="new-products-title">Sản phẩm mới nhất</h2>
        <section class="new-products">
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad1", "Details")"><img src="https://myshoes.vn/image/cache/catalog/2024/adidas/ad4/giay-adidas-lite-racer-rebold-nam-navy-trang-01-800x800.jpg.webp" alt="GIÀY ADIDAS LITE RACER REBOLD NAM - NAVY TRẮNG" class="product-image"></a>

                <p>
                    Giày Adidas Advantage 2.0 Nam - Trắng Đen
                </p>
                <p class="original-price">Giá gốc: <span class="line-through">1.800.000₫</span></p>
                <div class="discount-percentage">Giảm 28% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.290.000₫ VNĐ</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad2", "Details")"> <img src="~/Content/IMG/Adidas/GIÀY ADIDAS LITE RACER REBOLD NAM - XÁM.jpg" alt="GIÀY ADIDAS LITE RACER REBOLD NAM - XÁM" class="product-image"></a>

                <p>GIÀY ADIDAS LITE RACER REBOLD NAM - XÁM</p>
                <p class="original-price">Giá gốc: <span class="line-through">1.800.000₫</span></p>
                <div class="discount-percentage">Giảm 28% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.290.000₫ VNĐ</span></p>

            </div>
            <!-- Các sản phẩm mẫu bổ sung -->
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad3", "Details")"> <img src="~/Content/IMG/Adidas/GIÀY ADIDAS LITE RACER CLN 2.0 NAM - XANH NAVY.jpg" alt="GIÀY ADIDAS LITE RACER CLN 2.0 NAM - XANH NAVY" class="product-image"></a>
                <p>GIÀY ADIDAS LITE RACER CLN 2.0 NAM - XANH NAVY</p>
                <p class="original-price">Giá gốc: <span class="line-through">1.600.000₫</span></p>
                <div class="discount-percentage">Giảm 19% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">2.390.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad4", "Details")"><img src="~/Content/IMG/Adidas/GIÀY ADIDAS GRAND COURT SE NAM - ĐEN TRẮNG.jpg" alt="GIÀY ADIDAS GRAND COURT SE NAM - ĐEN TRẮNG" class="product-image"></a>

                <p>GIÀY ADIDAS GRAND COURT SE NAM - ĐEN TRẮNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.000.000₫</span></p>
                <div class="discount-percentage">Giảm 26% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.490.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad5", "Details")"> <img src="~/Content/IMG/Adidas/GIÀY ADIDAS ADVANCOURT BASE NAM NỮ - TRẮNG XANH LÁ.jpg" alt="GIÀY ADIDAS ADVANCOURT BASE NAM NỮ - TRẮNG XANH LÁ" class="product-image"></a>

                <p>GIÀY ADIDAS ADVANCOURT BASE NAM NỮ - TRẮNG XANH LÁ</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.000.000₫</span></p>
                <div class="discount-percentage">Giảm 21% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.590.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad6", "Details")"><img src="~/Content/IMG/Adidas/GIÀY ADIDAS GRAND COURT BASE 2.0 NAM - TRẮNG ĐEN.jpg" alt="GIÀY ADIDAS GRAND COURT BASE 2.0 NAM - TRẮNG ĐEN" class="product-image"></a>

                <p>GIÀY ADIDAS GRAND COURT BASE 2.0 NAM - TRẮNG ĐEN</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.000.000₫</span></p>
                <div class="discount-percentage">Giảm 21% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.590.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad7", "Details")"> <img src="~/Content/IMG/Adidas/GIÀY ADIDAS GRAND COURT BASE 2.0 NỮ - TRẮNG HỒNG.jpg" alt="GIÀY ADIDAS GRAND COURT BASE 2.0 NỮ - TRẮNG HỒNG" class="product-image"></a>

                <p>GIÀY ADIDAS GRAND COURT BASE 2.0 NỮ - TRẮNG HỒNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.000.000₫</span></p>
                <div class="discount-percentage">Giảm 21% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.590.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad8", "Details")"><img src="~/Content/IMG/Adidas/GIÀY ADIDAS GRAND COURT BASE 2.0 NAM NỮ - TRẮNG.jpg" alt="GIÀY ADIDAS GRAND COURT BASE 2.0 NAM NỮ - TRẮNG" class="product-image"></a>

                <p>GIÀY ADIDAS GRAND COURT BASE 2.0 NAM NỮ - TRẮNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.000.000₫</span></p>
                <div class="discount-percentage">Giảm 21% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.590.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad9", "Details")"> <img src="~/Content/IMG/Adidas/GIÀY ADIDAS GALAXY 7 NAM - TRẮNG XÁM.jpg" alt="GIÀY ADIDAS GALAXY 7 NAM - TRẮNG XÁM" class="product-image"></a>

                <p>GIÀY ADIDAS GALAXY 7 NAM - TRẮNG XÁM</p>
                <p class="original-price">Giá gốc: <span class="line-through">1.800.000₫</span></p>
                <div class="discount-percentage">Giảm 6% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.690.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spad10", "Details")"><img src="~/Content/IMG/Adidas/GIÀY ADIDAS GALAXY 7 NAM - ĐEN TRẮNG.jpg" alt="GIÀY ADIDAS GALAXY 7 NAM - ĐEN TRẮNG" class="product-image"></a>

                <p>GIÀY ADIDAS GALAXY 7 NAM - ĐEN TRẮNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">1.800.000₫</span></p>
                <div class="discount-percentage">Giảm 6% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.690.000₫</span></p>
            </div>
        </section>
    </div>
</body>
</html>

ThucHanhLanCuoi/Views/TrangGiay/TrangGiayTheThao.cshtml
@{
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trang Sale</title>
    <link rel="stylesheet" href="~/CSS/ProductTrungBai.css">
</head>
<body>


    <h1 class="page-title">Siêu Sale </h1>

    <div class="products-section">
        <h2 class="new-products-title">Sản phẩm đang sale</h2>
        <section class="new-products">
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <img src="~/Content/IMG/Nike/GIÀY NIKE REVOLUTION 7 NAM - ĐEN CAM.jpg" alt="GIÀY NIKE REVOLUTION 7 NAM - ĐEN CAM" class="product-image">
                <p>
                    GIÀY NIKE REVOLUTION 7 NAM - ĐEN CAM
                </p>
                <p class="original-price">Giá gốc: <span class="line-through">1.950.000₫</span></p>
                <div class="discount-percentage">Giảm 13% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.690.000₫ VNĐ</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <img src="~/Content/IMG/Nike/GIÀY NIKE COURT VISION LOW NAM - XANH DƯƠNG.jpg" alt="GIÀY NIKE COURT VISION LOW NAM - XANH DƯƠNG" class="product-image">
                <p>GIÀY NIKE COURT VISION LOW NAM - XANH DƯƠNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2,500,000 VNĐ</span></p>
                <div class="discount-percentage">Giảm 24% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1,890,000 VNĐ</span></p>

            </div>
            <!-- Các sản phẩm mẫu bổ sung -->
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <img src="~/Content/IMG/Nike/GIÀY NIKE AIR MAX EXCEE NỮ - HỒNG.jpg" alt="GIÀY NIKE AIR MAX EXCEE NỮ - HỒNG" class="product-image">
                <p>GIÀY NIKE AIR MAX EXCEE NỮ - HỒNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2,950,000 VNĐ</span></p>
                <div class="discount-percentage">Giảm 19% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">2.390.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <img src="~/Content/IMG/Nike/GIÀY NIKE AIR MAX EXCEE NỮ - TRẮNG.jpg" alt="GIÀY NIKE AIR MAX EXCEE NỮ - TRẮNG" class="product-image">
                <p>GIÀY NIKE AIR MAX EXCEE NỮ - TRẮNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.950.000₫</span></p>
                <div class="discount-percentage">Giảm 22% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">2.290.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <img src="~/Content/IMG/Lacoste/GIÀY LACOSTE LINESET NAM - TRẮNG XANH.jpg" alt="GIÀY LACOSTE LINESET NAM - TRẮNG XANH" class="product-image">
                <p>
                    GIÀY LACOSTE LINESET NAM - TRẮNG XANH
                </p>
                <p class="original-price">Giá gốc: <span class="line-through">3.150.000₫</span></p>
                <div class="discount-percentage">Giảm 27% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">2.290.000₫ VNĐ</span></p>
            </div>
        </section>
    </div>
</body>
</html>

ThucHanhLanCuoi/Views/TrangGiay/TrangNike.cshtml
@{
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trang bán giày Nike</title>
    <link rel="stylesheet" href="~/CSS/Product.css">
</head>
<body>


    <h1 class="page-title">Siêu Sale Giày Nike</h1>

    <div class="products-section">
        <h2 class="new-products-title">Sản phẩm mới nhất</h2>
        <section class="new-products">
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk1", "GiayNike")"><img src="~/Content/IMG/Nike/GIÀY NIKE REVOLUTION 7 NAM - ĐEN CAM.jpg" alt="GIÀY NIKE REVOLUTION 7 NAM - ĐEN CAM" class="product-image"></a>
                GIÀY NIKE REVOLUTION 7 NAM - ĐEN CAM
                </p>
                <p class="original-price">Giá gốc: <span class="line-through">1.950.000₫</span></p>
                <div class="discount-percentage">Giảm 13% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.690.000₫ VNĐ</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk2", "GiayNike")"> <img src="~/Content/IMG/Nike/GIÀY NIKE COURT VISION LOW NAM - XANH DƯƠNG.jpg" alt="GIÀY NIKE COURT VISION LOW NAM - XANH DƯƠNG" class="product-image"></a>
                <p>GIÀY NIKE COURT VISION LOW NAM - XANH DƯƠNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2,500,000 VNĐ</span></p>
                <div class="discount-percentage">Giảm 24% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1,890,000 VNĐ</span></p>

            </div>
            <!-- Các sản phẩm mẫu bổ sung -->
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk3", "GiayNike")"><img src="~/Content/IMG/Nike/GIÀY NIKE AIR MAX EXCEE NỮ - HỒNG.jpg" alt="GIÀY NIKE AIR MAX EXCEE NỮ - HỒNG" class="product-image"></a>
                <p>GIÀY NIKE AIR MAX EXCEE NỮ - HỒNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2,950,000 VNĐ</span></p>
                <div class="discount-percentage">Giảm 19% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">2.390.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk4", "GiayNike")"><img src="~/Content/IMG/Nike/GIÀY NIKE AIR MAX EXCEE NỮ - TRẮNG.jpg" alt="GIÀY NIKE AIR MAX EXCEE NỮ - TRẮNG" class="product-image"></a>
                <p>GIÀY NIKE AIR MAX EXCEE NỮ - TRẮNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.950.000₫</span></p>
                <div class="discount-percentage">Giảm 22% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">2.290.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk5", "GiayNike")"><img src="~/Content/IMG/Nike/GIÀY NIKE GRANDSTAND 2 NAM - XÁM NÂU.jpg" alt="GIÀY NIKE GRANDSTAND 2 NAM - XÁM NÂU" class="product-image"></a>
                <p>GIÀY NIKE GRANDSTAND 2 NAM - XÁM NÂU</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.830.000₫</span></p>
                <div class="discount-percentage">Giảm 12% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">2.430.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk6", "GiayNike")"> <img src="~/Content/IMG/Nike/GIÀY NIKE PROMINA NỮ - HỒNG.jpg" alt="GIÀY NIKE PROMINA NỮ - HỒNG" class="product-image"></a>
                <p>GIÀY NIKE PROMINA NỮ - HỒNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.400.000₫</span></p>
                <div class="discount-percentage">Giảm 17% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.990.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk7", "GiayNike")"><img src="~/Content/IMG/Nike/GIÀY NIKE PROMINA NAM - TRẮNG ĐEN.jpg" alt="GIÀY NIKE PROMINA NAM - TRẮNG ĐEN" class="product-image"></a>
                <p>GIÀY NIKE PROMINA NAM - TRẮNG ĐEN</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.400.000₫</span></p>
                <div class="discount-percentage">Giảm 17% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.990.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk8", "GiayNike")"><img src="~/Content/IMG/Nike/GIÀY NIKE PROMINA NAM - ĐEN TRẮNG.jpg" alt="GIÀY NIKE PROMINA NAM - ĐEN TRẮNG" class="product-image"></a>
                <p>GIÀY NIKE PROMINA NAM - ĐEN TRẮNG</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.400.000₫</span></p>
                <div class="discount-percentage">Giảm 17% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.990.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk9", "GiayNike")"><img src="~/Content/IMG/Nike/GIÀY NIKE DOWNSHIFTER 13 NỮ - XANH NGỌC.jpg" alt="GIÀY NIKE DOWNSHIFTER 13 NỮ - XANH NGỌC" class="product-image"></a>
                <p>GIÀY NIKE DOWNSHIFTER 13 NỮ - XANH NGỌC</p>
                <p class="original-price">Giá gốc: <span class="line-through">2.300.000₫</span></p>
                <div class="discount-percentage">Giảm 13% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.990.000₫</span></p>
            </div>
            <div class="product-item">
                <div class="labels">
                    <div class="label new-arrival">HÀNG MỚI VỀ</div>
                    <div class="label sale">SIÊU SALE</div>
                </div>
                <a href="@Url.Action("spnk10", "GiayNike")"> <img src="https://myshoes.vn/image/cache/catalog/2024/nike/nk6/giay-nike-revolution-7-nam-trang-xanh-01-800x800.jpg.webp" class="product-image"></a>
                <p>Giày Nike Revolution 7 Nam - Trắng Xanh</p>
                <p class="original-price">Giá gốc: <span class="line-through">1.950.000₫</span></p>
                <div class="discount-percentage">Giảm 13% </div>
                <p class="current-price">Giá hiện tại: <span class="current-price-value">1.690.000₫</span></p>
            </div>
        </section>
    </div>
</body>
</html>